// Ref: https://firebase.google.com/docs/auth/admin/errors?hl=fr

export enum FirebaseAuthError {
  FIREBASE_AUTH_USER_NOT_FOUND = "auth/user-not-found",
  FIREBASE_AUTH_CLAIMS_TOO_LARGE = "auth/claims-too-large", // La charge utile des revendications fournie à setCustomUserClaims() dépasse la taille maximale autorisée de 1 000 octets.
  FIREBASE_AUTH_EMAIL_ALREADY_EXISTS = "auth/email-already-exists", // L'adresse e-mail fournie est déjà utilisée par un utilisateur existant. Chaque utilisateur doit avoir un email unique.
  FIREBASE_AUTH_ID_TOKEN_EXPIRED = "auth/id-token-expired", // Le jeton d'identification Firebase fourni a expiré.
  FIREBASE_AUTH_ID_TOKEN_REVOKED = "auth/id-token-revoked", // Le jeton d'identification Firebase a été révoqué.
  FIREBASE_AUTH_INSUFFICIENT_PERMISSION = "auth/insufficient-permission", // Les informations d'identification utilisées pour initialiser le SDK Admin ne disposent pas d'une autorisation suffisante pour accéder à la ressource d'authentification demandée. Reportez-vous à Configurer un projet Firebase pour obtenir de la documentation sur la façon de générer un identifiant avec les autorisations appropriées et de l'utiliser pour authentifier les SDK Admin.
  FIREBASE_AUTH_INTERNAL_ERROR = "auth/internal-error", // Le serveur d'authentification a rencontré une erreur inattendue lors de la tentative de traitement de la demande. Le message d'erreur doit contenir la réponse du serveur d'authentification contenant des informations supplémentaires. Si l'erreur persiste, veuillez signaler le problème à notre canal d'assistance Bug Report .
  FIREBASE_AUTH_INVALID_ARGUMENT = "auth/invalid-argument", //Un argument non valide a été fourni à une méthode d'authentification. Le message d'erreur doit contenir des informations supplémentaires.
  FIREBASE_AUTH_INVALID_CLAIMS = "auth/invalid-claims", // Les attributs de revendication personnalisés fournis à setCustomUserClaims() ne sont pas valides.
  FIREBASE_AUTH_INVALID_CONTINUE_URI = "auth/invalid-continue-uri ", //L'URL de continuation doit être une chaîne d'URL valide.
  FIREBASE_AUTH_INVALID_CREATION_TIME = "auth/invalid-creation-time", // L'heure de création doit être une chaîne de date UTC valide.
  FIREBASE_AUTH_INVALID_CREDENTIAL = "auth/invalid-credential", //Les informations d'identification utilisées pour authentifier les SDK d'administration ne peuvent pas être utilisées pour effectuer l'action souhaitée. Certaines méthodes d'authentification telles que createCustomToken() et verifyIdToken() nécessitent que le SDK soit initialisé avec des informations d'identification de certificat, par opposition à un jeton d'actualisation ou des informations d'identification par défaut de l'application. Voir Initialiser le SDK pour obtenir de la documentation sur la façon d'authentifier les SDK d'administration avec des informations d'identification de certificat.
  FIREBASE_AUTH_INVALID_DISABLED_FIELD = "auth/invalid-disabled-field", //La valeur fournie pour la propriété de l'utilisateur disabled n'est pas valide. Ce doit être un booléen.
  FIREBASE_AUTH_INVALID_DISPLAY_NAME = "auth/invalid-display-name", //La valeur fournie pour la propriété utilisateur displayName n'est pas valide. Il doit s'agir d'une chaîne non vide.
  FIREBASE_AUTH_INVALID_DYNAMIC_LINK_DOMAIN = "auth/invalid-dynamic-link-domain", //Le domaine de lien dynamique fourni n'est pas configuré ou autorisé pour le projet en cours.
  FIREBASE_AUTH_INVALID_INVALID_EMAIL = "auth/invalid-email", //La valeur fournie pour la propriété d'utilisateur de email n'est pas valide. Il doit s'agir d'une adresse e-mail de chaîne.
  FIREBASE_AUTH_INVALID_INVALID_EMAIL_VERIFIED = "auth/invalid-email-verified", //La valeur fournie pour la propriété utilisateur emailVerified n'est pas valide. Ce doit être un booléen.
  FIREBASE_AUTH_INVALID_INVALID_HASH_ALGORITHM = "auth/invalid-hash-algorithm", //L'algorithme de hachage doit correspondre à l'une des chaînes de la liste des algorithmes pris en charge.
  FIREBASE_AUTH_INVALID_INVALID_HASH_BLOCK_SIZE = "auth/invalid-hash-block-size", //La taille du bloc de hachage doit être un nombre valide.
  FIREBASE_AUTH_INVALID_HASH_DERIVED_KEY_LENGTH = "auth/invalid-hash-derived-key-length", //La longueur de la clé dérivée du hachage doit être un nombre valide.
  FIREBASE_AUTH_INVALID_HASH_KEY = "auth/invalid-hash-key", //La clé de hachage doit être un tampon d'octets valide.
  FIREBASE_AUTH_INVALID_HASH_MEMORY_COST = "auth/invalid-hash-memory-cost", //Le coût de la mémoire de hachage doit être un nombre valide.
  FIREBASE_AUTH_INVALID_HASH_PARALLELIZATION = "auth/invalid-hash-parallelization", //La parallélisation de hachage doit être un nombre valide.
  FIREBASE_AUTH_INVALID_HASH_ROUNDS = "auth/invalid-hash-rounds", //Les tours de hachage doivent être un nombre valide.
  FIREBASE_AUTH_INVALID_HASH_SALT_SEPARATOR = "auth/invalid-hash-salt-separator", //Le champ séparateur de sel de l'algorithme de hachage doit être un tampon d'octets valide.
  FIREBASE_AUTH_INVALID_ID_TOKEN = "auth/invalid-id-token", //Le jeton d'identification fourni n'est pas un jeton d'identification Firebase valide.
  FIREBASE_AUTH_INVALID_LAST_SIGN_IN_TIME = "auth/invalid-last-sign-in-time", //L'heure de la dernière connexion doit être une chaîne de date UTC valide.
  FIREBASE_AUTH_INVALID_PAGE_TOKEN = "auth/invalid-page-token", //Le jeton de page suivante fourni dans listUsers() n'est pas valide. Il doit s'agir d'une chaîne non vide valide.
  FIREBASE_AUTH_INVALID_PASSWORD = "auth/invalid-password", //La valeur fournie pour la propriété utilisateur du password de passe n'est pas valide. Il doit s'agir d'une chaîne d'au moins six caractères.
  FIREBASE_AUTH_INVALID_PASSWORD_HASH = "auth/invalid-password-hash", //Le hachage du mot de passe doit être un tampon d'octets valide.
  FIREBASE_AUTH_INVALID_PASSWORD_SALT = "auth/invalid-password-salt", //Le mot de passe salt doit être un tampon d'octets valide
  FIREBASE_AUTH_INVALID_PHONE_NUMBER = "auth/invalid-phone-number", //La valeur fournie pour le numéro de phoneNumber n'est pas valide. Il doit s'agir d'une chaîne d'identifiant non vide conforme à la norme E.164.
  FIREBASE_AUTH_INVALID_PHOTO_URL = "auth/invalid-photo-url", //La valeur fournie pour la propriété utilisateur photoURL n'est pas valide. Il doit s'agir d'une URL de chaîne.
  FIREBASE_AUTH_INVALID_PROVIDER_DATA = "auth/invalid-provider-data", //Le providerData doit être un tableau valide d'objets UserInfo.
  FIREBASE_AUTH_INVALID_PROVIDER_ID = "auth/invalid-provider-id", //Le providerId doit être une chaîne d'identifiant de fournisseur prise en charge valide.
  FIREBASE_AUTH_INVALID_OAUTH_RESPONSETYPE = "auth/invalid-oauth-responsetype", //Un seul type de responseType OAuth doit être défini sur true.
  FIREBASE_AUTH_INVALID_SESSION_COOKIE_DURATION = "auth/invalid-session-cookie-duration", //La durée du cookie de session doit être un nombre valide en millisecondes entre 5 minutes et 2 semaines.
  FIREBASE_AUTH_INVALID_UID = "auth/invalid-uid", //L' uid fourni doit être une chaîne non vide d'au plus 128 caractères.
  FIREBASE_AUTH_INVALID_USER_IMPORT = "auth/invalid-user-import", //L'enregistrement d'utilisateur à importer n'est pas valide.
  FIREBASE_AUTH_MAXIMUM_USER_COUNT_EXCEEDED = "auth/maximum-user-count-exceeded", //Le nombre maximum d'utilisateurs autorisés à importer a été dépassé.
  FIREBASE_AUTH_MISSING_ANDROID_PKG_NAME = "auth/missing-android-pkg-name", //Un nom de package Android doit être fourni si l'application Android doit être installée.
  FIREBASE_AUTH_MISSING_CONTINUE_URL = "auth/missing-continue-uri", //Une URL de continuation valide doit être fournie dans la demande.
  FIREBASE_AUTH_MISSING_HASH_ALGORITHM = "auth/missing-hash-algorithm", //L'importation d'utilisateurs avec des hachages de mot de passe nécessite que l'algorithme de hachage et ses paramètres soient fournis.
  FIREBASE_AUTH_MISSING_IOS_BUNDLE_ID = "auth/missing-ios-bundle-id", //Il manque un ID de bundle à la demande.
  FIREBASE_AUTH_MISSING_UID = "auth/missing-uid", //Un identifiant uid est requis pour l'opération en cours.
  FIREBASE_AUTH_MISSING_OAUTH_CLIENT_SECRET = "auth/missing-oauth-client-secret", //Le secret du client de configuration OAuth est requis pour activer le flux de code OIDC.
  FIREBASE_AUTH_OPERATION = "auth/operation-not-allowed", //Le fournisseur de connexion fourni est désactivé pour votre projet Firebase. Activez -le dans la section Méthode de connexion de la console Firebase.
  FIREBASE_AUTH_PHONE_NUMBER_ALREADY_EXISTS = "auth/phone-number-already-exists", //Le phoneNumber fourni est déjà utilisé par un utilisateur existant. Chaque utilisateur doit avoir un phoneNumber unique.
  FIREBASE_AUTH_PROJECT_NOT_FOUND = "auth/project-not-found", //Aucun projet Firebase n'a été trouvé pour les informations d'identification utilisées pour initialiser les SDK d'administration. Reportez-vous à Configurer un projet Firebase pour obtenir de la documentation sur la façon de générer un identifiant pour votre projet et de l'utiliser pour authentifier les SDK Admin.
  FIREBASE_AUTH_RESERVED_CLAIMS = "auth/reserved-claims", //Une ou plusieurs revendications utilisateur personnalisées fournies à setCustomUserClaims() sont réservées. Par exemple, les revendications spécifiques à OIDC telles que (sub, iat, iss, exp, aud, auth_time, etc.) ne doivent pas être utilisées comme clés pour les revendications personnalisées.
  FIREBASE_AUTH_SESSION_COOKIE_EXPIRED = "auth/session-cookie-expired", //Le cookie de session Firebase fourni a expiré.
  FIREBASE_AUTH_SESSION_COOKIE_REVOKED = "auth/session-cookie-revoked", //Le cookie de session Firebase a été révoqué.
  FIREBASE_AUTH_UID_ALREADY_EXISTS = "auth/uid-already-exists", //L' uid fourni est déjà utilisé par un utilisateur existant. Chaque utilisateur doit avoir un uid unique.
  FIREBASE_AUTH_UNAUTHORIZED_CONTINUE_URL = "auth/unauthorized-continue-uri", //Le domaine de l'URL de continuation n'est pas sur la liste blanche. Ajoutez le domaine à la liste blanche dans la console Firebase.
}
